package com.yunniu.lease.dao;

import com.yunniu.lease.model.OrderSub;

public interface OrderSubMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ordersub
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ordersub
     *
     * @mbggenerated
     */
    int insert(OrderSub record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ordersub
     *
     * @mbggenerated
     */
    int insertSelective(OrderSub record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ordersub
     *
     * @mbggenerated
     */
    OrderSub selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ordersub
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OrderSub record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ordersub
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OrderSub record);
}